### ISSUE TITLE
Deprecation of .live() function

### ISSUE THREAD

**Issue by ip-rob** [meta100/mColorPicker#11]
I've noticed this code getting used by others in Wordpress plugins. In that environment, there are warnings about the deprecation of the .live() function. I replaced that function with .on() modifying the formatting. Is there a way to get this incorporated into the official branch? Or is this project dead based on the last update dates?

Rob
[mColorPicker_min.zip](https://github.com/meta100/mColorPicker/files/5396384/mColorPicker_min.zip)

**Comment by meta100** [comment]
live() has been updated to on() per your request. I did not know the plugin was still in use.
